spring:
  application:
    name: User Management App

  server:
    port: 8080

  liquibase:
    change-log: classpath:liquibase/liquibase-changelog.xml
    default-schema: ${my.db.schemaname}
    liquibase-schema: ${my.db.schemaname}

  datasource:
    name: Database connection - ${my.db.schemaname}
    url: jdbc:mysql://localhost:3306/
    username: root
    password: $password$
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: ${my.db.schemaname}

my:
  db:
    schema-name: uma_db